ShortTitle:
  category: title
  245:
    subfields:
      - [a]
SubTitle:
  category: title
  245:
    subfields:
      - [b]
TitleSection:
  category: title
  245:
    subfields:
      - [n]
    p:
      - [name, extended]
TitleStatement:
  category: title
  245:
    subfields:
      - [c]
WorkTitle:
  category: title
  130:
    a:
      - [name, title]
      - [replace, '@', '']
  240:
    a:
      - [name, title]
      - [replace, '@', '']
  100:
    a:
      - [name, person]
    c:
      - [name, titles]
    d:
      - [name, dates] 
OtherTitles:
  category: title
  246:
    subfields:
      - [a]
PreviousTitles:
  category: title
  780:
    t:
      - [name, title]
    w:
      - [name, id]
      - [match, '\(DE-(599)|(600)\)([0-9xX-]+)', 3]
NewerTitlesFromMarc:
  category: title
  785:
    t:
      - [name, title]
    w:
      - [name, id]
      - [match, '\(DE-(599)|(600)\)([0-9xX-]+)', 3]
Person:
  category: person
  100:
    a:
      - [name, name]
    b:
      - [name, number]
    c:
      - [name, title]
    d:
      - [name, date]
    e:
      - [name, description]
      - [replace, 'in( |$)$', 'In ']
      - [function, 'ucfirst']
  700:
    a:
      - [name, name]
    b:
      - [name, number]
    c:
      - [name, title]
    d:
      - [name, date]
    e:
      - [name, description]
      - [replace, 'in( |$)$', 'In ']
      - [function, 'ucfirst']
DeduplicatedCooperations:
  category: person
  110:
    a:
      - [name, name]
    b:
      - [name, unit]
    c:
      - [name, location]
    d:
      - [name, date]
    e:
      - [name, description]
      - [function, 'ucfirst']
  710:
    a:
      - [name, name]
    b:
      - [name, unit]
    c:
      - [name, location]
    d:
      - [name, date]
    e:
      - [name, description]
      - [function, 'ucfirst']
CongressData:
  category: person
  111:
    a:
      - [name, name]
    c:
      - [name, location]
    d:
      - [name, date]
    e:
      - [name, unit]
  711:
    a:
      - [name, name]
    c:
      - [name, location]
    d:
      - [name, date]
    e:
      - [name, unit]
Performers:
  category: person
  511:
    subfields:
      - [a]
Summary:
  category: description
  520:
    subfields:
      - [a]
Formats:
  category: description
  '000':
    parent:
      - [getFormats]
Languages:
  category: description
  546:
    parent:
      - [getLanguages]
    subfields:
      - [a]
OriginalLanguage:
  category: description
  '041':
    subfields:
      - [a]
PublicationDetails:
  category: description
  264:
    a:
      - [name, location]
      - [replace, ' ;.*$', '']
    b:
      - [name, name]
    c:
      - [name, date]
  362:
    a:
      - [name, date]
  260:
    a:
      - [name, location]
      - [replace, ' ;.*$', '']
    b:
      - [name, name]
    c:
      - [name, date]
#  980:
#    conditions:
#      - [field, 2, 22]
#    g:
#      - [name, date]
Series:
  category: title
  490:
    subfields:
    a:
      - [name, title]
      - [match, '^([^<>]+)( <([^<>]+)>(.*))?$', 1]
    a:
      - [name, supplement]
      - [match, '^([^<>]+)( <([^<>]+)>(.*))?$', 3]
    v:
      - [name, volume]
  830:
    subfields:
    v:
      - [name, volume]
    w:
      - [name, ppn]
      - [match, '\(DE-601\)([0-9xX]+)', 1]





UniversityNotes:
  category: title
  502:
    a:
      - [name, note]
    b:
      - [name, item]
    c:
      - [name, place]
    d:
      - [name, date]
IncludedItems:
  501:
    subfields:
      - [a]
NLM:
  category: class
  '060':
    subfields:
      - [a]
BasicClassifications:
  category: class
  '084':
    conditions:
      - [field, 2, bcl]
    subfields:
      - [a, 9]
FormNote:
  category: description
  655:
    subfields:
      - [a]
GeneralNotes:
  category: description
  500:
    subfields:
      - [a]
PhysicalDescription:
  category: description
  300:
    subfields:
      - [a, b, c, e]
MapInfos:
  category: description
  255:
    subfields:
      - [a, b, c, d, e, f, g]
SystemDetails:
  category: description
  520:
    subfields:
      - [a]
Citations:
  '024':
    subfields:
      - [a]
Fingerprints:
  '026':
    subfields:
      - [a]
LocationOfOriginal:
  535:
    subfields:
      - [a]
ContainingWork:
  773:
    i:
      - [name, prefix]
    t:
      - [name, title]
    z:
      - [name, isn]
      - [match, '\(.+\)([^()]+)', 1]
    x:
      - [name, isn]
      - [match, '\(.+\)([^()]+)', 1]
    w:
      - [name, ppn]
      - [match, '\(.+\)([^()]+)', 1]
    d:
      - [name, location]
    g:
      - [name, issue]
  800:
    i:
      - [name, prefix]
    t:
      - [name, title]
    z:
      - [name, isn]
      - [match, '\(.+\)([^()]+)', 1]
    x:
      - [name, isn]
      - [match, '\(.+\)([^()]+)', 1]
    w:
      - [name, ppn]
      - [match, '\(.+\)([^()]+)', 1]
    d:
      - [name, location]
    g:
      - [name, issue]
URLs:
  856:
    conditions:
      - [field, y, !C]
    u:
      - [name, url]
    3:
       - [name, description]
    z:
      - [name, description]
  555:
    conditions:
      - [field, y, !C]
    u:
      - [name, url]
    a:
       - [name, description]
RelationshipNotes:
  580:
    subfields:
      - [a]
ISBNs:
  '020':
    9:
      - [name, isbn]
ISSNs:
  '022':
    a:
      - [match, '([0-9xX-]+)', 1]
SecondaryEditions:
  533:
    subfields:
      - [a, b, c, d, f]
    e:
      - [name, content]
OtherEditions:
  787:
    conditions:
      - [field, i, '*']
    i:
      - [name, fieldType]
    t:
      - [name, fieldDesc]
    w:
      - [name, type]
      - [replace, '^\(DE-600\).+$', 'ZDBID']
      - [replace, '^\(DE-601\).+$', 'PPN']
    w:
      - [name, id]
      - [match, '\(DE-60[01]\)([^()]+)', 1]
SignatureData:
  980:
    conditions:
      - [field, 2, '22']
    d:
      - [name, signature]
    e:
      - [name, indicator]
    f:
      - [name, sigel]
    k:
      - [name, foot_note]
    x:
      - [name, licence_note]
    y:
      - [name, location_note]
LicenceData:
  981:
    conditions:
      - [field, 2, '22']
    y:
      - [name, licence_type]
CollectionDetails:
  912:
    subfields:
      - [a]
